/* Config.hh. Generated by CMake for ignition-utils. */

/* Version number */
#define IGNITION_UTILS_MAJOR_VERSION 1
#define IGNITION_UTILS_MINOR_VERSION 5
#define IGNITION_UTILS_PATCH_VERSION 1

#define IGNITION_UTILS_VERSION "1.5"
#define IGNITION_UTILS_VERSION_FULL "1.5.1"

#define IGNITION_UTILS_VERSION_NAMESPACE v1

#define IGNITION_UTILS_VERSION_HEADER "Gazebo utils, version 1.5.1\nCopyright (C) 2020 Open Source Robotics Foundation.\nReleased under the Apache 2.0 License.\n\n"

/* #undef IGNITION_UTILS_BUILD_TYPE_PROFILE */
/* #undef IGNITION_UTILS_BUILD_TYPE_DEBUG */
/* #undef IGNITION_UTILS_BUILD_TYPE_RELEASE */

namespace ignition
{
}

namespace gz
{
  using namespace ignition;
}
